/* Static portfolio generator. Project records remain in legacy-build-site.js
   temporarily as a data source; rendering is deliberately defined only here. */
const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadData(){const source=fs.readFileSync(path.join(__dirname,'legacy-build-site.js'),'utf8')+';module.exports={projects,toolkit,pro,unavailable};';const silentFs={...fs,writeFileSync:()=>{}};const mod={exports:{}};vm.runInNewContext(source,{require:n=>n==='fs'?silentFs:require(n),module:mod,exports:mod.exports,__dirname,__filename:path.join(__dirname,'legacy-build-site.js'),process,console,Buffer,setTimeout,clearTimeout});return mod.exports}
const {projects,toolkit,pro,unavailable}=loadData();
const VERIFIED='2026-08-14'; // only projects explicitly audited against README/docs use this date
const PRIMITIVES_VERIFIED='2026-08-28';
const REPO_VERIFIED='2026-09-16';
// Axiom One is a deliberately separate family: these projects are compact
// primitives which can be used independently instead of a wider framework.
const primitive=(slug,name,problem,solution,tags,use,limits,code,flow,evidence,repo,platform='Portable C99; caller-owned state and no dynamic allocation')=>({slug,name,group:'Axiom One primitives',problem,solution,status:'Development',version:null,lastVerified:PRIMITIVES_VERIFIED,license:'MIT',language:'C99',platform,tags,use,limits,code,flow,evidence,repo});
const primitives=[
  primitive('axiom-one','Axiom One',
    'Embedded applications repeatedly need small, well-bounded control, signal, sequence and state operations without adopting a framework or paying for unused code.',
    'A dependency-free C99 static library of 22 focused deterministic primitives. Its ONE modules keep state with the caller, use no heap, timers, callbacks or I/O, and expose a plain C API that can be included as one umbrella header or as narrow module headers.',
    ['deterministic primitives','no heap','caller-owned state','C99'],
    ['Apply bounded slew, hysteresis, filtering or quantization to a control signal','Arbitrate work, generate a fractional rate or calculate capped retry delay','Track freshness, replay windows, cyclic sequence numbers or K-of-N votes','Use fixed-capacity buffers, packed fields, sets, records and traces without a general container framework'],
    ['It is a collection of independent primitives, not an RTOS, scheduler, hardware abstraction layer or application framework','Mutable one_*_t objects remain owned and synchronized by the caller','Callers must check documented status values and preserve each API’s numeric-domain contracts'],
    '#include <one.h>\n\nuint32_t current = 0u;\n(void)one_slew_u32(100u, 10u, 20u, &current);\n/* current advances toward 100 by at most 10 on this call. */',
    'Application-owned state → focused ONE module → explicit result → application policy',
    ['22 independent modules are exposed through one.h; using the umbrella header does not pull every module into a static-linked binary','The module family covers scheduling; signal and numeric operations; sequence and protocol handling; and fixed-capacity state containers','Repository documentation records Debug, Release, AddressSanitizer and MSVC /W4 /WX test configurations, plus a linker-map-based footprint report'],
    'https://github.com/Vanderhell/axiom-one'),
  primitive('graygyre','GrayGyre',
    'Adjacent logical indices can cluster in the same page, bank or logical cell even when a small deterministic spread would improve placement.',
    'An allocation-free, table-free C primitive maps indices with a self-inverse Gray-code shear, spreading local neighbours across configured logical cells while retaining an exact inverse through the same mapping call.',
    ['Gray code','data placement','branchless','table-free'],
    ['Spread deterministic record placement across logical pages or banks','Place DMA descriptors or burst-interleaved data without lookup tables','Map an index repeatedly in a hot loop after one configuration step','Permute an array in place without a visited bitmap'],
    ['Not encryption, cryptography, hashing, wear levelling, error correction or a full-cycle scheduler','The domain size must be a power of two','The mapping contains fixed points; it is a placement permutation, not a traversal order'],
    '#include "graygyre.h"\n\ngraygyre_config cfg;\ngraygyre_config_init(&cfg, 256u, 4u);\nuint32_t physical = graygyre_map_config(logical, &cfg);\nuint32_t original = graygyre_map_config(physical, &cfg);\n/* original == logical: the transform is self-inverse. */',
    'Logical index → Gray-code shear → logical cell + local offset → physical index',
    ['Configured mapping is branchless, integer-only and has no hidden state','ESP32-S3 hardware measurements and a tested configured-map size are documented separately from optimisation-profile caveats','Cortex-M0+/M4/M33 and RV32I/RV32IM are documented as compile/static-validated targets'],
    'https://github.com/Vanderhell/GrayGyre'),
  primitive('skipspace','SkipSpace',
    'Large constrained search spaces are often implicit: materialising the tree or retaining every explored prefix exceeds embedded memory budgets.',
    'A heap-free traversal primitive represents each prefix with compact sufficient state, counts valid continuations using bounded saturating arithmetic, and lets the caller visit or skip an entire subtree without materialising the search tree.',
    ['implicit search','subtree skipping','heap-free','saturating count'],
    ['Traverse a modeled constrained space with fixed caller-owned workspace','Count a subtree before deciding whether to visit or skip it','Keep navigation state compact when equivalent prefixes have equivalent futures','Use sparse skip checks in a large deterministic exploration'],
    ['It is not a general solver, AI framework, vector database or universal search engine','The modeled transition table must preserve future-relevant behaviour in its sufficient state','count/can_skip cost substantially more than push/pop; V1 does not put rank/unrank on the hot path'],
    '#include "skipspace.h"\n\n/* Configure the modeled transition table and caller-owned workspace. */\n/* push() updates sufficient state; count()/can_skip() decide a subtree. */\n/* No search tree is allocated or materialised. */',
    'Prefix → sufficient state → bounded subtree count → visit or skip subtree',
    ['The portable C core has no Arduino or ESP-IDF dependency and no dynamic allocation','V1 defines navigation, bounded/saturating count, can_skip and workspace sizing, with depth bounded at 1000','An ESP32-S3 uint32_t, 31-state, K=32 profile is documented with approximately 227,834 visited nodes/s using sparse skip checks'],
    'https://github.com/Vanderhell/skipspace')
];
Object.assign(unavailable,{problem:'Trainable text compression benefits from frequency-aware coding rather than a fixed generic codec.',solution:'Pure C99, MIT trainable frequency-optimized text codec with v2 and matrix-based v3 formats, including HIER4/HIER8 nested matrices.',status:'v0.4.3',version:'v0.4.3',lastVerified:VERIFIED,license:'MIT',language:'C99',platform:'Portable C99; external, embedded and amortized deployment objectives',tags:['text codec','trainable','matrix v3'],use:['Train from representative text','Use v2 or matrix-based v3 streams','Choose a documented deployment objective'],limits:['Compression trade-offs depend on the selected corpus and objective','Benchmark interpretation requires the documented corpus and configuration'],code:'#include "loxc.h"\n/* Train or load a documented model, then encode/decode via the public API. */',flow:'Training corpus → codec model → encode/decode API → v2 or v3 stream',evidence:['README documents trainer, CLI, simple API, examples, tests, benchmarks and technical documentation','v3 documents HIER4/HIER8 nested matrices and diagonal cells that save one coordinate value'],repo:'https://github.com/Vanderhell/loxc'});
Object.assign(projects.find(p=>p.slug==='microcrypt'),{status:'v3.0.1',version:'v3.0.1',solution:'C99 cryptographic primitives: SHA-256, HMAC-SHA256, AES-128, AES-128-CBC and AES-128-GCM with AEAD, AAD and secure-clearing helpers.',tags:['crypto primitives','AEAD'],use:['Hash a firmware buffer','Compute and verify HMAC-SHA256','Use AES-128-GCM through its documented AEAD interface'],limits:['No audit, proof, FIPS or side-channel-resistance claim','Table-based AES is unsuitable against observable cache/timing/power attackers','Follow documented nonce and key requirements'],evidence:['Repository documents tests, verification information and the v3.0.1 API surface']});
for(const p of [...projects,toolkit,pro,unavailable]){if(p.version==='Development')p.version=null;p.version??=(p.status.match(/v\d+(?:\.\d+)+/)||[null])[0];p.tags=[...new Set(p.tags||[])];delete p.lastVerified;}
// A micro* repository belongs in the Micro Toolkit even when its original
// source record used the catch-all project group.
for(const p of [...projects,toolkit])if(/^micro/i.test(p.slug))p.group='Micro-toolkit';
unavailable.lastVerified=VERIFIED;
projects.find(p=>p.slug==='microcrypt').lastVerified=VERIFIED;
const newProjects=[
 {slug:'basalt-net',name:'Basalt.NET',group:'Beyond LOX',problem:'Applications need durable background work with local storage or a shared SQL Server queue.',solution:'A .NET durable job, scheduling and static-workflow engine with embedded storage or SQL Server backends, retry and idempotent enqueue, leases, fencing, crash recovery and a separate WPF management dashboard.',status:'Development',license:'MIT',language:'C#',platform:'.NET 8; .NET Framework 4.7.2 / WPF consumer support; Embedded or SQL Server',tags:['durable jobs','scheduling','.NET','SQL Server'],use:['Run durable typed jobs in one application with embedded storage','Share a durable queue between processes through SQL Server','Schedule delayed, interval, daily or cron work','Compose statically defined workflow DAGs','Inspect queue health, executions, failures, schedules and workers through management APIs and BasaltDashboard'],limits:['Execution is at least once; handlers with external side effects need idempotency or appropriate fencing','SQL Server storage is not a worker service: each executing process registers handlers and starts the runtime','BasaltDashboard is a separate WPF management console'],code:'using var basalt = Basalt.Embedded(@"C:\\data\\jobs");\nbasalt.On<SendInvoice>("billing.send", HandleAsync);\nawait basalt.StartAsync();\nawait basalt.EnqueueAsync(new SendInvoice(123), key: "invoice:123", retry: 5);',flow:'Typed job → durable embedded or SQL Server queue → leased worker → handler → recorded outcome',evidence:['README documents delayed, interval, daily and cron scheduling, static DAG workflows, retries, idempotent enqueue, recovery, leases and fencing','README documents .NET 8 and .NET Framework 4.7.2 / WPF consumer support','Management/monitoring documentation describes health, queue, execution, schedule, workflow and worker APIs; BasaltDashboard uses the managed API','Durability documentation explicitly specifies at-least-once execution'],repo:'https://github.com/Vanderhell/Basalt.NET',version:null,lastVerified:REPO_VERIFIED},
 {slug:'nexum',name:'Nexum',group:'Beyond LOX',problem:'Communication behaviors such as routing, filtering, acknowledgements and retries often become dedicated runtime operations.',solution:'An experimental programmable communication fabric built around a deterministic execution primitive and explicit bounded state transitions, composed into graphs through caller-provided FIFO storage.',status:'Experimental',license:'MPL-2.0',language:'C11',platform:'Portable C11; caller-owned or fixed bounded graph, state, queue and output storage',tags:['deterministic runtime','programmable fabric','research'],use:['Model a bounded state transition as P_config(state, event) → (next_state, bounded_outputs)','Compose graph primitives and execute them in FIFO order','Use Program IR, the builder and compiler helpers to declare and lower programs','Represent time and randomness as explicit input events','Replay ordered event traces under the documented D1/D2 guarantees'],limits:['Experimental research software; not production-ready, a complete network stack or a transport protocol','D3 schedule-independent determinism is not guaranteed for every graph; it is a conservative graph-analysis result','Queue capacity, output capacity and execution budgets are explicit','Tests and sanitizer runs do not constitute formal verification or a security proof'],code:'#include "nexum_compile.h"\n\nnexum_compile_spec_t spec = {0};\nnexum_compile_requirements_t requirements;\nnexum_program_t program;\nspec.behavior = (uint8_t)NEXUM_BEHAVIOR_PASS;\nif (nexum_compile_requirements(&spec, &requirements) != PNP_OK) return 1;\nif (nexum_compile(&spec, requirements.capacities, &program) != PNP_OK) return 1;',flow:'Builder and compiler helpers → Program IR → deterministic lowering → FIFO graph runtime → bounded state transition',evidence:['README specifies P_config(state, event) → (next_state, bounded_outputs), fixed-width explicit state domains and deterministic IDs/routing order','Primitive and graph execution do not allocate; queues, graph arrays, domains and output buffers are caller-owned or fixed bounded storage','README defines D1 primitive and D2 ordered replay determinism; D3 is conditional graph analysis','CTest covers semantics, FIFO order, replay, generated cases, serialization, retry, IR, builder and compiler helpers; separate workflows cover fuzzing and Clang ASan/UBSan'],repo:'https://github.com/Vanderhell/Nexum',version:null,lastVerified:REPO_VERIFIED},
 {slug:'implicitnet',name:'ImplicitNet',group:'Beyond LOX',problem:'Some deterministic network and routing experiments need a graph model without allocating and storing every edge.',solution:'An experimental, allocation-free C17 library that computes mappings, dimension-based neighbors, deterministic next hops and reversible state updates directly from compact state, without materializing the graph.',status:'Experimental',license:'MIT',language:'C17',platform:'C17; supported power-of-two network sizes from 4 through 65,536 nodes',tags:['implicit networks','routing','deterministic'],use:['Map and unmap node identifiers through inverse state-derived bijections','Compute implicit neighbors by dimension','Choose a deterministic next hop toward a target','Apply and reverse an event-derived network state transition'],limits:['Valid network size must be a power of two in [4, 65,536]','Invalid value-returning calls use UINT32_MAX; state-changing calls report failure','Experimental library; no cryptographic security or universally optimal routing claim'],code:'#include "implicit_net.h"\nin_state state;\nif (!in_init(&state, 1024, UINT64_C(0x1234))) return 1;\nuint32_t next_hop = in_next(17, 900, 1024, state);',flow:'Power-of-two node count + 64-bit state → implicit map / neighbor / next-hop operation → node result',evidence:['README documents C17 with no heap allocation, recursion, dependencies or mutable global state','Supported sizes are N=2^w from 4 through 65,536; in_map/in_unmap are inverses and in_step/in_prev reverse with the same event','CTest includes C invariant tests and an optional Python reference-oracle cross-check with randomized consistency and routing checks'],repo:'https://github.com/Vanderhell/ImplicitNet',version:null,lastVerified:REPO_VERIFIED},
 {slug:'compost',name:'Compost',group:'Beyond LOX',problem:'The project explores whether simple deterministic local rules can produce interesting global behavior in an artificial-life sandbox.',solution:'An experimental deterministic artificial-life simulator and complex-systems research project. Autonomous mathematical organisms consume binary input as FOOD, maintain internal state, energy and metabolism, grow structural bodies, hold territory, reproduce, die and compete for resources.',status:'Experimental',license:'MIT',language:'Python',platform:'Python 3.11+; sandbox runtime with persistent world state and telemetry',tags:['artificial life','complex systems','research'],use:['Run reproducible experiments over supplied binary inputs','Observe world snapshots, FOOD accounting, population, body mass, organism reserves and territory','Compare outcomes under deterministic local lifecycle and resource rules'],limits:['Not a biological model','Not a production data-processing system','Experimental research project; results depend on implemented rules, parameters and captured inputs','Telemetry is observational and may be eventually consistent while workers run'],code:'python -m pip install .\npython -m mathematical_organism run sandbox --workers 4 --max-seconds 30\npython -m mathematical_organism status sandbox --organisms',flow:'Binary inbox input → experiment-owned FOOD and world → deterministic organism rules → persistent state and observational telemetry',evidence:['README defines FOOD as binary input and organisms as mathematical simulator abstractions with state, energy, body, territory and lifecycle transitions','Runtime copies inbox files to experiment-owned storage, advances local rules, persists world state and writes telemetry','README explicitly says the project is not a biological model or production data-processing system; pyproject requires Python 3.11+ and declares version 0.1.0'],repo:'https://github.com/Vanderhell/Compost',version:'v0.1.0',lastVerified:REPO_VERIFIED}
];
Object.assign(newProjects.find(p=>p.slug==='basalt-net'),{version:'v1.1.0'});
// License audit rule: an explicit repository LICENSE is primary evidence.
// GitHub's SPDX detector is only supplemental metadata (LOX Dust: MIT LICENSE).
Object.assign(projects.find(p=>p.slug==='loxdust'),{license:'MIT'});
Object.assign(projects.find(p=>p.slug==='loxdb'),{
  status:'v1.5.3',version:'v1.5.3',
  solution:'Predictable-memory C99 database with key-value, time-series and small relational engines, optional WAL recovery, and direct installation from PlatformIO or the Arduino Library Manager.',
  channels:['PlatformIO Registry','Arduino Library Manager'],
  use:['Install it from the PlatformIO Registry','Find and install loxdb in the Arduino Library Manager','Store configuration or binary state by key','Keep typed telemetry streams with retention policies','Use small indexed fixed-schema tables','Recover a storage-backed database after an interrupted write'],
  evidence:['The public repository publishes PlatformIO library.json and Arduino library.properties manifests','595 microtest cases across 61 C test files plus one C++ wrapper test are documented by the current repository','Evidence matrix separates source-visible, host-tested and hardware claims','ESP32-S3 published measurements use an in-RAM flash-like backend, not physical NOR or brownout testing']
});
projects.find(p=>p.slug==='loxdb').lastVerified='2026-08-17';
Object.assign(projects.find(p=>p.slug==='ironfamily-fileengine'),{repo:'https://github.com/Vanderhell/IronFamily.FileEngine'});
const status=p=>{const s=p.status.toLowerCase();return s.includes('commercial')?'Commercial':s.includes('experiment')?'Experimental':s.includes('verification')||s.includes('repair')?'Verification':/not declared release-ready|unreleased|pre-1\.0/.test(s)?'Development':s.includes('release')||/^v\d/.test(s)?'Stable':'Development'};
const head=(title,description,url,p='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="google-site-verification" content="ZcLes6Gcp4HDDqHMF7uUlssy00WjDbP_rXlndEgeJZw"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://vanderhell.github.io/${url}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="https://vanderhell.github.io/${url}"><meta property="og:image" content="https://vanderhell.github.io/lox-logo.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${p}favicon.svg"><link rel="stylesheet" href="${p}assets/site.css"><script defer src="${p}analytics-config.js"></script><script defer src="${p}assets/analytics.js"></script><script defer src="${p}assets/site.js"></script></head>`;
const nav=(p='',current='')=>`<a class="skip" href="#main">Skip to content</a><header class="site-header"><nav class="nav wrap" aria-label="Main navigation"><a class="brand" href="${p}index.html"><span class="site-title">Vanderhell <strong>Development</strong><small>C · C++ · C# · Embedded Systems</small></span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="nav-links">Menu</button><div class="nav-links" id="nav-links"><a href="${p}index.html" ${current==='home'?'aria-current="page"':''}>Home</a><a href="${p}lox-family.html">LOX Family</a><a href="${p}micro-toolkit.html">Micro Toolkit</a><a href="${p}axiom-one.html">Axiom One</a><a href="${p}beyond-lox.html">Beyond LOX</a><a href="${p}about.html">About</a><a href="https://github.com/Vanderhell">GitHub</a></div></nav></header>`;
const footer=p=>`<footer class="site-footer"><div class="wrap footer-row"><span>© 2026 Vanderhell</span><a href="mailto:Vanderhell@gmail.com">Vanderhell@gmail.com</a></div></footer>`;
const card=(p,prefix='')=>{prefix=typeof prefix==='string'?prefix:'';const meta=[status(p),p.version,p.language,p.license].filter(Boolean).map(esc).join(' · ');return `<article class="portfolio-card" data-project-card data-group="${esc(p.group)}"><h3>${esc(p.name)}</h3><p>${esc(p.solution)}</p><small>${meta}</small><a href="${prefix}projects/${p.slug}.html">Open project</a></article>`};
const flow=p=>`<div class="flow">${p.flow.split('→').map((x,i)=>`<span><b>${i+1}</b>${esc(x.trim())}</span>`).join('<i>→</i>')}</div>`;
const detail=p=>{const scenarios=new Set(['loxdb','loxbudget','microsh','loxboot','iotspool','panicdump']);const hasScenario=scenarios.has(p.slug);const versionBadge=p.version?`<span class="badge">${esc(p.version)}</span>`:'';return `${head(`${p.name} — Vanderhell portfolio`,`${p.name}: ${p.problem}` ,`projects/${p.slug}.html`,'../')}<body data-project="${p.slug}">${nav('../')}<main id="main"><header class="hero product-hero"><div class="wrap"><div class="kicker">${esc(p.group)}</div><h1>${esc(p.name)}</h1><p class="slogan">${esc(p.problem)}</p><p>${esc(p.solution)}</p><div class="badges"><span class="badge status-${status(p).toLowerCase()}">${status(p)}</span>${versionBadge}<span class="badge">${esc(p.license)}</span><span class="badge">${esc(p.language)}</span></div><div class="actions"><a class="button primary" href="${p.repo}">GitHub</a><a class="button secondary" href="#quick-start">Quick Start</a></div><dl class="meta"><div><dt>Last verified</dt><dd>${p.lastVerified}</dd></div><div><dt>Platform scope</dt><dd>${esc(p.platform)}</dd></div></dl></div></header><section class="section"><div class="wrap content-grid"><article class="content"><h2>What it solves</h2><p>${esc(p.problem)}</p><h2>How it works</h2>${flow(p)}<h2>Use it when</h2><div class="use-grid">${p.use.map(x=>`<div class="panel">${esc(x)}</div>`).join('')}</div><h2 id="quick-start">Quick Start</h2><div class="code-wrap"><pre><code>${esc(p.code)}</code></pre></div>${hasScenario?`<h2>Real scenarios</h2><div class="scenario-stack">${p.use.slice(0,3).map((x,i)=>`<section class="scenario"><span class="scenario-no">0${i+1}</span><h3>${esc(x)}</h3><p>${esc(p.solution)}</p></section>`).join('')}</div>`:''}<h2>Engineering evidence</h2><ul>${p.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Known limits</h2><ul>${p.limits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><aside class="side panel"><strong>Project data</strong><a href="${p.repo}">Repository ↗</a><p><small>Verified ${p.lastVerified}</small></p></aside></div></section></main>${footer('../')}</body></html>`};
const groups=[['LOX Family',projects.filter(p=>p.group==='LOX')],['Micro Toolkit',projects.filter(p=>p.group==='Micro-toolkit')],['Axiom One primitives',primitives],['Beyond LOX',[...projects.filter(p=>p.group==='Beyond LOX'),...newProjects]]];
const specialExplainers={
 'basalt-net':`<h2>Durability and execution</h2><p>Jobs are durably accepted before handlers run. Recovery, leases and fencing coordinate work across restarts and SQL Server clients. Execution is at least once, so handlers with external side effects need idempotency or suitable fencing.</p><h2>Scheduling and workflows</h2><p>Supports delayed, interval, daily and cron scheduling, with timezone, overlap and misfire policies. Workflows are statically declared durable DAGs with explicit dependencies and dependency-failure policies.</p><h2>Storage and management</h2><p>Embedded storage fits a local application or machine. SQL Server lets multiple processes share a queue; each process executing work registers handlers and starts Basalt. BasaltDashboard is a separate WPF console; the management/monitoring API exposes health, queues, executions, failures, schedules, workflows, workers and cumulative statistics through the managed API.</p>`,
 'nexum':`<h2>Primitive and graph model</h2><p>A primitive evaluates <code>P_config(state, event) → (next_state, bounded_outputs)</code>. Configuration selects inputs, an ALU operation, predicate, optional state/event-field updates and bounded output masks. Program IR separates logical cells, state domains, edges, inputs and outputs from runtime array addresses.</p><h2>Build and execute</h2><p>The builder assigns deterministic identifiers and routing order; compiler helpers express foundational compositions. Lowering creates a graph over caller-provided arrays and graph execution uses FIFO order. Time and randomness are explicit events. Primitive and graph execution do not allocate; program, queues, domains, graph arrays and outputs use caller-owned or fixed bounded storage.</p><h2>Determinism and validation</h2><p>D1 is primitive determinism and D2 is ordered replay determinism. D3 schedule-independent determinism is a conservative graph-analysis result, not guaranteed for every graph. CTest coverage, fuzzing and sanitizer workflows are documented. Nexum is experimental research software, not production-ready or formally verified.</p>`,
 'implicitnet':`<h2>Implicit network operations</h2><p>For supported power-of-two node counts, nodes and links are derived from network size and a 64-bit state. The API provides inverse <code>in_map</code>/<code>in_unmap</code>, dimension-based implicit neighbors, deterministic <code>in_next</code> routing, and reversible <code>in_step</code>/<code>in_prev</code> event transitions. The graph is never materialized.</p><h2>Memory and verification</h2><p>The C17 library has no heap allocation, recursion, dependencies or mutable global state. C invariant tests and Python reference-oracle tests cross-check randomized mapping and routing behavior. ImplicitNet remains experimental and makes no cryptographic security or universally optimal routing claim.</p>`,
 'compost':`<h2>World model</h2><p>Compost treats binary input as FOOD in the simulator's terminology. Organisms are autonomous mathematical entities with internal state, energy/metabolism, structural bodies and territory, plus deterministic reproduction and death transitions. These describe simulator bookkeeping, not biological processes.</p><h2>Sandbox runtime and experiments</h2><p>Inbox files are copied into experiment-owned storage, partitioned into FOOD, and processed under local rules for resources, growth, maintenance, territory and competition. The runtime persists world state and writes observational telemetry; the observer reports state rather than directing organisms. Captured experiments and supplied inputs support reproducible comparisons; live telemetry may be eventually consistent.</p><p class="notice">Experimental artificial-life and complex-systems research project. Not a biological model or production data-processing system.</p>`
};
const specialDetail=p=>{const version=p.version?`<span class="badge">${esc(p.version)}</span>`:'';return `${head(`${p.name} — Vanderhell portfolio`,`${p.name}: ${p.problem}`,`projects/${p.slug}.html`,'../')}<body data-project="${p.slug}">${nav('../')}<main id="main"><header class="hero product-hero"><div class="wrap"><div class="kicker">${esc(p.group)}</div><h1>${esc(p.name)}</h1><p class="slogan">${esc(p.problem)}</p><p>${esc(p.solution)}</p><div class="badges"><span class="badge status-${status(p).toLowerCase()}">${status(p)}</span>${version}<span class="badge">${esc(p.license)}</span><span class="badge">${esc(p.language)}</span></div><div class="actions"><a class="button primary" href="${p.repo}">GitHub repository</a><a class="button secondary" href="#quick-start">Example</a></div><dl class="meta"><div><dt>Last verified</dt><dd>${p.lastVerified}</dd></div><div><dt>Platform / runtime</dt><dd>${esc(p.platform)}</dd></div></dl></div></header><section class="section"><div class="wrap content-grid"><article class="content"><h2>Purpose</h2><p>${esc(p.problem)}</p><h2>Execution model</h2>${flow(p)}${specialExplainers[p.slug]}<h2>Typical use</h2><div class="use-grid">${p.use.map(x=>`<div class="panel">${esc(x)}</div>`).join('')}</div><h2 id="quick-start">Quick start</h2><div class="code-wrap"><pre><code>${esc(p.code)}</code></pre></div><h2>Repository evidence</h2><ul>${p.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Limits and status</h2><ul>${p.limits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p><a href="../all-projects.html">All projects</a> · <a href="../beyond-lox.html">Additional projects</a></p></article><aside class="side panel"><strong>Project data</strong><a href="${p.repo}">GitHub repository</a><p>${esc(p.status)} · ${esc(p.language)} · ${esc(p.license)}</p><p><small>Verified ${p.lastVerified}</small></p></aside></div></section></main>${footer('../')}</body></html>`};
const axiomModules=[
 ['ONEARB','Round-robin arbiter','Scheduling','Stateful','eligible bit mask → arbiter cursor → selected winner','one_arb_init, one_arb_next','Caller initializes and retains arbiter state; winner exists only when an eligible request is selected.','Select fairly among currently eligible bounded work items.'],
 ['ONEBACKOFF','Saturating exponential delay','Retry timing','Stateless','base delay + attempt + maximum → capped delay','one_backoff_delay','Returns a bounded arithmetic delay; it does not schedule or wait.','Calculate a retry delay before passing it to an application timer.'],
 ['ONEBUF','Single producer/consumer state buffer','Buffer coordination','Stateful','operation + capacity/value → buffer state → status and indices/generation','one_buf','Coordinates state only; payload storage and concurrency discipline belong to the caller.','Coordinate a single producer/consumer handoff over caller-owned data.'],
 ['ONEDBUF','Two-slot producer/consumer buffer','Buffer coordination','Stateful','operation + two-slot state → publish/release result','one_dbuf','Only coordination state is provided; the caller owns payload storage and synchronization context.','Publish a new value while retaining a ready slot or selecting documented drop-old policy.'],
 ['ONEDEAD','Dead-zone transform','Signal conditioning','Stateless','signed/unsigned sample + bounds → output','one_dead_u32, one_dead_i32','Configured interval and numeric type define the accepted domain.','Suppress small sensor deviations by mapping the configured interval to zero.'],
 ['ONEEMA','Integer exponential moving average','Signal filtering','Stateful','sample + EMA state → updated filtered value','one_ema_init, one_ema_update','Caller owns initialized filter state; smoothing shift controls the documented integer update.','Smooth a noisy sampled sensor signal.'],
 ['ONEFIELD','Packed fixed-width values','Compact storage','Stateful descriptor','range + width + caller bytes; ID/value → packed bytes or decoded value','one_field_init_range, one_field_set_u32, one_field_get_u32','Backing storage is caller supplied and must meet the required size and range/width contract.','Store small configuration fields in a bounded byte array.'],
 ['ONEHYST','Two-threshold hysteresis','Signal conditioning','Stateful','sample + low/high thresholds + binary state → updated state','one_hyst_i32, one_hyst_u32','Requires low < high and state 0 or 1; state holds between thresholds.','Prevent a threshold-controlled output from chattering near one boundary.'],
 ['ONEIDX','Numeric or symbolic key to index','Lookup mapping','Stateful descriptor','configured range/keys + ID/key → bounded slot index','one_idx_init_range, one_idx_index_u32','Provides lookup mapping, not payload storage; caller defines the valid range or symbols.','Map stable IDs to offsets in an application-owned array.'],
 ['ONEINIT','Ordered initialization runner','Startup sequencing','Stateless','ordered function array → invoke each function in order','one_init_run','Runs supplied functions in order; initialization functions and their effects are caller-defined.','Express driver initialization before application initialization.'],
 ['ONEOUTLIER','Accepted-sample delta guard','Input validation','Stateful','sample + accepted reference + max delta → accept/reject and reference update','one_outlier_init, one_outlier_accept','The initial accepted reference and maximum delta define the acceptance rule.','Reject a sudden measurement outside the configured delta from the last accepted sample.'],
 ['ONEQUANT','Nearest grid point','Numeric conversion','Stateless','signed/unsigned value + origin/step → snapped value','one_quant_i32, one_quant_u32','Numeric types and step domain are part of the API contract.','Quantize a control or measurement value to a fixed increment.'],
 ['ONERATE','Fractional event-rate generator','Rate generation','Stateful','numerator/denominator + phase → updated phase and emit flag','one_rate_step','Caller retains phase; each call advances one deterministic phase step.','Generate an event on three of every ten calls without a fractional timer.'],
 ['ONESCALE','Integer range conversion','Numeric conversion','Stateless','input range + output range + value → checked or clamped output','one_scale_u32 and signed/unsigned checked/clamp variants','Checked forms report out-of-range input; clamp variants map to an endpoint.','Convert a bounded ADC reading into a PWM range.'],
 ['ONESEQ','Cyclic sequence domain','Sequence arithmetic','Stateful configuration','bit width + sequence value → next/previous/distance/comparison','one_seq_init_bits, one_seq_next','Half-capacity distance is explicitly ambiguous; callers must check documented status.','Advance an 8-bit sequence from 255 back to 0 with explicit cyclic rules.'],
 ['ONESET','Packed membership set','Bounded container','Stateful descriptor','range + caller bytes; ID/key/index → add/remove/contains result','one_set_init_range, one_set_add_u32, one_set_contains_u32','Storage is caller allocated and sized through the required-byte API.','Track membership in a small fixed set without a general container.'],
 ['ONESLEW','Bounded step toward target','Control signal','Stateless with caller value','target + rise/fall limits + current value → bounded updated value','one_slew_i32, one_slew_u32','Zero limit is a hold; the operation does not overshoot the target.','Limit command movement per control-loop iteration.'],
 ['ONESTALE','Wrap-safe timestamp freshness','Freshness check','Stateless','now tick + updated tick + maximum age → fresh/stale result','one_stale_check','Maximum age must be below 0x80000000 to avoid half-range ambiguity.','Check freshness in a wrapping 32-bit tick counter.'],
 ['ONESTAT','Packed multi-field records','Bounded records','Stateful descriptor','record/field schema + caller bytes + operation → packed field result','one_stat_init_range, one_stat_get_u32, one_stat_add_u32','Field widths, required byte capacity and saturating arithmetic follow the schema contract.','Maintain compact bounded per-channel counters or small record sets.'],
 ['ONETRACE','Fixed-capacity ring trace','Diagnostics','Stateful descriptor','caller bytes + event → bounded ring; index → chronological entry','one_trace_init, one_trace_push, one_trace_get','Storage and record width are caller supplied; pushing when full overwrites the oldest entry.','Retain a compact recent event history for failure diagnosis.'],
 ['ONEVOTE','K-of-N sliding vote','Filtering / voting','Stateful','window size + threshold + boolean sample → rolling vote result','one_vote_init, one_vote_push','Window and threshold are configured and retained in caller-owned state.','Require three valid readings among the most recent five samples.'],
 ['ONEWINDOW','32-packet replay window','Protocol sequence filtering','Stateful','packet sequence + 32-bit window state → new/duplicate/old/ambiguous classification','one_window_reset, one_window_accept','Packets older than 31 positions and half-range ambiguous sequences are classified explicitly.','Reject duplicate or too-old sequence numbers in a bounded packet receive window.']
].map(([name,purpose,category,state,model,api,limits,typical])=>({name,purpose,category,state,model,api,limits,typical,id:name.toLowerCase()}));
const axiomCards=axiomModules.map(m=>`<article class="primitive-card"><span class="tag">${esc(m.category)}</span><h3>${esc(m.name)}</h3><p>${esc(m.purpose)}.</p><dl><dt>State</dt><dd>${esc(m.state)}</dd><dt>Model</dt><dd>${esc(m.model)}</dd></dl><a href="#${m.id}">Read ${esc(m.name)} details</a></article>`).join('');
const axiomDetails=axiomModules.map(m=>`<section class="primitive-detail" id="${m.id}"><h3>${esc(m.name)} — ${esc(m.purpose)}</h3><dl><dt>Category</dt><dd>${esc(m.category)}</dd><dt>State</dt><dd>${esc(m.state)}</dd><dt>Model</dt><dd>${esc(m.model)}</dd><dt>Public API</dt><dd><code>${esc(m.api)}</code></dd><dt>Typical use</dt><dd>${esc(m.typical)}</dd><dt>Limits</dt><dd>${esc(m.limits)}</dd></dl></section>`).join('');
const family=(name,list,file)=>`${head(`${name} — Vanderhell Development`,`${name} in the Vanderhell project portfolio.`,file)}<body>${nav('')}<main id="main"><header class="hero compact-hero"><div class="wrap"><div class="kicker">Project family</div><h1>${name}</h1></div></header><section class="section"><div class="wrap"><div class="portfolio-cards">${list.map(p=>card(p)).join('')}</div></div></section></main>${footer('')}</body></html>`;
const additionalLanding=`${head('Additional projects — Vanderhell Development','Independent systems, infrastructure and experimental research projects.','beyond-lox.html')}<body>${nav('')}<main id="main"><header class="hero compact-hero"><div class="wrap"><div class="kicker">Independent systems projects</div><h1>Additional projects</h1><p>Specialised infrastructure, deterministic research and embedded tools outside the LOX and Micro Toolkit families.</p></div></header><section class="section"><div class="wrap"><h2>Systems and infrastructure</h2><div class="portfolio-cards">${newProjects.filter(p=>p.slug==='basalt-net').map(p=>card(p)).join('')}</div><h2>Deterministic and research projects</h2><div class="portfolio-cards">${newProjects.filter(p=>p.slug!=='basalt-net').map(p=>card(p)).join('')}</div><h2>Other independent projects</h2><div class="portfolio-cards">${projects.filter(p=>p.group==='Beyond LOX').map(p=>card(p)).join('')}</div></div></section></main>${footer('')}</body></html>`;
const axiomFamily=`${head('Axiom One primitives — Vanderhell Development','Deterministic, allocation-free C primitives for bounded embedded problems.','axiom-one.html')}<body>${nav('')}<main id="main"><header class="hero compact-hero"><div class="wrap"><div class="kicker">Primitive family</div><h1>Axiom One primitives</h1><p>Three independent building blocks for bounded embedded work: a broad deterministic module library, table-free data placement, and heap-free traversal of implicit constrained spaces.</p></div></header><section class="section"><div class="wrap content-narrow"><h2>Small primitives, explicit boundaries</h2><p>This family is intentionally not a framework. Each component solves one narrow problem with deterministic behaviour, caller-owned state and no hidden allocation. They can stand alone in firmware where memory, timing and integration boundaries matter.</p><div class="portfolio-cards">${primitives.map(p=>card(p)).join('')}</div><h2>How the pieces differ</h2><div class="use-grid"><div class="panel"><strong>Axiom One</strong><br>22 general-purpose C99 primitives for scheduling, signal conditioning, protocol state and fixed-capacity containers.</div><div class="panel"><strong>GrayGyre</strong><br>A self-inverse Gray-code placement transform that spreads neighbouring indices across logical cells.</div><div class="panel"><strong>SkipSpace</strong><br>A sufficient-state traversal core that counts and skips subtrees without constructing the search tree.</div></div></div></section></main>${footer('')}</body></html>`;
const selected=['loxdb','basalt-net','nexum','loxc','axiom-one','umesh'].map(s=>s==='loxc'?unavailable:projects.find(p=>p.slug===s)||newProjects.find(p=>p.slug===s)||primitives.find(p=>p.slug===s));
const axiomCatalogPage=(url='axiom-one.html')=>`${head('Axiom One — deterministic C primitives','Axiom One is a portable C99 library of 22 independent deterministic primitives with caller-owned state and bounded interfaces.',url)}<body>${nav('')}<main id="main"><header class="hero compact-hero"><div class="wrap"><div class="kicker">Primitive library · portable C99</div><h1>Axiom One</h1><p>A dependency-free static library of 22 independent embedded-focused primitives. Each has a plain C API and a bounded problem scope; the umbrella header is convenient, while static linking includes only referenced module objects.</p><p>Modules retain state in caller-owned objects where state is required. Modules do not allocate heap memory, perform I/O or acquire hidden time/random inputs. They provide no timer or callback service; ONEINIT explicitly runs the ordered function list supplied by its caller. Stateless helpers remain stateless; inputs, outputs, state updates and error results are explicit in each API contract.</p><div class="badges"><span class="badge">22 modules</span><span class="badge">C99</span><span class="badge">MIT</span></div><div class="actions"><a class="button primary" href="https://github.com/Vanderhell/axiom-one">GitHub repository</a><a class="button secondary" href="#primitive-catalog">Browse primitives</a></div></div></header><section class="section"><div class="wrap"><h2>Axiom One as a library</h2><p class="lede">Composable, portable plain C building blocks for constrained systems. Caller-owned storage and state make ownership visible. Each operation accepts explicit inputs and returns explicit results; no hidden clock, random source or global mutable state is introduced by the modules.</p><p>Debug, Release, AddressSanitizer and MSVC warning-as-error test configurations are documented. A footprint report uses linker-map evidence for selected static library objects. These properties do not remove each module's documented domain, capacity or synchronization responsibilities.</p><h2 id="primitive-catalog">Axiom One primitives</h2><p>Each card links to the module's purpose, state model, API, typical use and limits below.</p><div class="primitive-grid">${axiomCards}</div><h2>Module details</h2>${axiomDetails}<p>Related independent projects: <a href="projects/graygyre.html">GrayGyre</a> and <a href="projects/skipspace.html">SkipSpace</a>. They remain separate repositories and portfolio projects.</p><p><a href="all-projects.html">All projects</a></p></div></section></main>${footer('')}</body></html>`;
const home=`${head('Vanderhell Development — systems and embedded software','Native systems and embedded software: storage, recovery, diagnostics and communication.','index.html')}<body>${nav('','home')}<main id="main"><header class="hero portfolio-hero"><div class="wrap"><div class="kicker">Independent systems software development</div><h1>Vanderhell Development</h1><p class="lede">Small native components and systems for constrained environments: storage, recovery, diagnostics, communication and deterministic control.</p><div class="actions"><a class="button primary" href="#selected">Selected projects</a><a class="button secondary" href="https://github.com/Vanderhell">GitHub</a></div></div></header><section class="section"><div class="wrap"><h2>What I build</h2><div class="areas"><article class="area"><h3>Persistent systems</h3><p>Databases, logs, configuration and power-loss recovery.</p></article><article class="area"><h3>Diagnostics & recovery</h3><p>Crash evidence, watchdogs, boot recovery and alarms.</p></article><article class="area"><h3>Communication</h3><p>LAN, mesh, queues and constrained protocols.</p></article><article class="area"><h3>Low-level building blocks</h3><p>Deterministic C components with explicit ownership and limits.</p></article></div></div></section><section class="section selected" id="selected"><div class="wrap"><h2>Selected projects</h2><div class="portfolio-cards">${selected.map(p=>card(p)).join('')}</div></div></section><section class="section family-section"><div class="wrap"><h2>Project families</h2><div class="families"><a href="lox-family.html"><h3>LOX Family</h3><p>Persistent state, recovery and diagnostics.</p></a><a href="micro-toolkit.html"><h3>Micro Toolkit</h3><p>Small independent components.</p></a><a href="axiom-one.html"><h3>Axiom One primitives</h3><p>Focused deterministic primitives for embedded constraints.</p></a><a href="beyond-lox.html"><h3>Beyond LOX</h3><p>Specialised systems work.</p></a></div><p><a href="all-projects.html">Find a project by engineering problem →</a></p></div></section></main>${footer('')}</body></html>`;
const all=[...projects,...newProjects,...primitives,toolkit,pro,unavailable];
const catalog=`${head('All Projects — Vanderhell Development','Complete project catalogue of '+all.length+' public projects.','all-projects.html')}<body>${nav('')}<main id="main"><header class="hero compact-hero"><div class="wrap"><h1>All projects</h1><p>${all.length} public repository projects across storage, infrastructure, deterministic research, diagnostics, communication and embedded software.</p></div></header><section class="section"><div class="wrap"><label class="search-label">Search projects <input id="project-search" type="search"></label><div class="portfolio-cards catalog-cards">${all.map(card).join('')}</div><p class="empty" hidden>No matching project.</p></div></section></main>${footer('')}</body></html>`;
const about=`${head('About Vanderhell Development','Independent systems and embedded software development.','about.html')}<body>${nav('','about')}<main id="main"><header class="hero compact-hero"><div class="wrap"><h1>Systems software, with boundaries made explicit.</h1><p>Independent developer focused on C/C++, embedded systems and relevant C#/.NET tooling.</p></div></header><section class="section"><div class="wrap content-narrow"><h2>Engineering focus</h2><p>Architecture, implementation, tests, documentation and release engineering for storage, persistence, diagnostics, communication, deterministic behaviour and constrained systems.</p><h2>Representative work</h2><div class="portfolio-cards">${selected.slice(0,4).map(card).join('')}</div></div></section></main>${footer('')}</body></html>`;
const enhanceHome=text=>text
  .replace('<div class="kicker">Independent systems software development</div>','<div class="kicker" data-typewriter>Independent systems software development</div>')
  .replace('<h1>Vanderhell Development</h1>','<h1>Embedded systems that recover, explain and endure.</h1>')
  .replace('<h3>LOX Family</h3><p>Persistent state, recovery and diagnostics.</p>','<h3>LOX — Liquid Oxygen</h3><p>Liquid Oxygen for Embedded Systems: focused storage, recovery, control and diagnostic components.</p>')
  .replace('<p class="lede">Small native components and systems for constrained environments: storage, recovery, diagnostics, communication and deterministic control.</p>','<div class="hero-focus" data-hero-focus><p class="lede">Small native components and systems for constrained environments.</p><div class="focus-options" aria-label="Explore engineering focus"><button type="button" data-focus="storage" aria-pressed="true">Storage</button><button type="button" data-focus="recovery" aria-pressed="false">Recovery</button><button type="button" data-focus="diagnostics" aria-pressed="false">Diagnostics</button><button type="button" data-focus="communication" aria-pressed="false">Communication</button><button type="button" data-focus="control" aria-pressed="false">Deterministic control</button></div><p class="focus-output" aria-live="polite">Predictable persistence for configuration, telemetry and small structured data.</p></div>')
  .replace('<h2>Project families</h2><div class="families">',`<h2>Project families</h2><p class="family-intro">Four clear paths through the portfolio: product systems, micro libraries, deterministic primitives and specialised independent work.</p><div class="family-stats" aria-label="Project family totals"><span><b data-count="${groups[0][1].length}">0</b> LOX projects</span><span><b data-count="${groups[1][1].length}">0</b> micro libraries</span><span><b data-count="${groups[2][1].length}">0</b> primitives</span><span><b data-count="${groups[3][1].length}">0</b> additional projects</span></div><div class="families">`)
  .replace('<div class="actions"><a class="button primary" href="#selected">Selected projects</a><a class="button secondary" href="https://github.com/Vanderhell">GitHub</a></div>','<div class="actions hero-actions"><a class="button primary" href="#selected">Selected projects</a><a class="button secondary" href="all-projects.html">Find by engineering problem &rarr;</a><a class="button secondary" href="https://github.com/Vanderhell">GitHub</a></div>');
const enhanceLoxdb=text=>text.replace('<div class="badges">','<div class="install-channels" aria-label="Available package managers"><strong>Install from</strong><span>PlatformIO Registry</span><span>Arduino Library Manager</span><small>Search for <b>loxdb</b> in either library manager.</small></div><div class="badges">');
const enhanceLoxFamily=text=>text
  .replaceAll('LOX Family projects.','Liquid Oxygen for Embedded Systems: focused storage, recovery, control and diagnostic projects.')
  .replace('<h1>LOX Family</h1>','<h1>LOX — Liquid Oxygen for Embedded Systems</h1><p class="lox-manifesto">Small, explicit components that give constrained firmware room to recover, explain decisions and keep moving.</p><button class="rocket-launch" type="button" data-rocket-launch aria-label="Launch the LOX rocket"><span>Launch the LOX mission</span><svg viewBox="0 0 160 80" aria-hidden="true"><path class="rocket-route" d="M12 65C52 62 67 42 90 30s38-13 58-22"/><g class="rocket"><path d="M0-9C13-9 22-4 29 0 22 4 13 9 0 9L-7 0z"/><path d="M5-9l-6-8h10l8 9M5 9l-6 8h10l8-9"/><circle cx="12" cy="0" r="4"/></g><g class="rocket-flame"><path d="M-8 0l-11-6 4 6-4 6z"/></g></svg></button>');
const write=(file,text)=>fs.writeFileSync(path.join(ROOT,file),text.replaceAll('>LOX Family</a>','>LOX / Liquid Oxygen</a>').replaceAll('<div class="kicker">LOX</div>','<div class="kicker">LOX · Liquid Oxygen for Embedded Systems</div>').replaceAll('Beyond LOX','Additional projects').replaceAll('undefined','Not audited against current README/docs'));
write('index.html',enhanceHome(home));write('axiom-one.html',axiomCatalogPage());write('beyond-lox.html',additionalLanding);write('all-projects.html',catalog);
for(const p of all)write(`projects/${p.slug}.html`,p.slug==='loxdb'?enhanceLoxdb(detail(p)):newProjects.includes(p)?specialDetail(p):detail(p));
const urls=['','lox-family.html','micro-toolkit.html','axiom-one.html','beyond-lox.html','all-projects.html','about.html',...all.map(p=>`projects/${p.slug}.html`)];write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>https://vanderhell.github.io/${u}</loc></url>`).join('')}</urlset>`);write('robots.txt','User-agent: *\nAllow: /\nSitemap: https://vanderhell.github.io/sitemap.xml\n');
