/* Static portfolio generator. Project records remain in legacy-build-site.js
   temporarily as a data source; rendering is deliberately defined only here. */
const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..'), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadData(){const source=fs.readFileSync(path.join(__dirname,'legacy-build-site.js'),'utf8')+';module.exports={projects,toolkit,pro,unavailable};';const silentFs={...fs,writeFileSync:()=>{}};const mod={exports:{}};vm.runInNewContext(source,{require:n=>n==='fs'?silentFs:require(n),module:mod,exports:mod.exports,__dirname,__filename:path.join(__dirname,'legacy-build-site.js'),process,console,Buffer,setTimeout,clearTimeout});return mod.exports}
const {projects,toolkit,pro,unavailable}=loadData();
const VERIFIED='2026-08-14'; // only projects explicitly audited against README/docs use this date
const PRIMITIVES_VERIFIED='2026-08-28';
// Axiom One is a deliberately separate family: these projects are compact
// primitives which can be used independently instead of a wider framework.
const primitive=(slug,name,problem,solution,tags,use,limits,code,flow,evidence,repo,platform='Portable C99; caller-owned state and no dynamic allocation')=>({slug,name,group:'Axiom One primitives',problem,solution,status:'Development',version:null,lastVerified:PRIMITIVES_VERIFIED,license:'MIT',language:'C99',platform,tags,use,limits,code,flow,evidence,repo});
const primitives=[
  primitive('axiom-one','Axiom One',
    'Embedded applications repeatedly need small, well-bounded control, signal, sequence and state operations without adopting a framework or paying for unused code.',
    'A dependency-free C99 static library of 22 focused deterministic primitives. Its ONE modules keep state with the caller, use no heap, timers, callbacks or I/O, and expose a plain C API that can be included as one umbrella header or as narrow module headers.',
    ['deterministic primitives','no heap','caller-owned state','C99'],
    ['Apply bounded slew, hysteresis, filtering or quantization to a control signal','Arbitrate work, generate a fractional rate or calculate capped retry delay','Track freshness, replay windows, cyclic sequence numbers or K-of-N votes','Use fixed-capacity buffers, packed fields, sets, records and traces without a general container framework'],
    ['It is a collection of independent primitives, not an RTOS, scheduler, hardware abstraction layer or application framework','Mutable one_*_t objects remain owned and synchronized by the caller','Callers must check documented status values and preserve each API’s numeric-domain contracts'],
    '#include <one.h>\n\nuint32_t current = 0u;\n(void)one_slew_u32(100u, 10u, 20u, &current);\n/* current advances toward 100 by at most 10 on this call. */',
    'Application-owned state → focused ONE module → explicit result → application policy',
    ['22 independent modules are exposed through one.h; using the umbrella header does not pull every module into a static-linked binary','The module family covers scheduling; signal and numeric operations; sequence and protocol handling; and fixed-capacity state containers','Repository documentation records Debug, Release, AddressSanitizer and MSVC /W4 /WX test configurations, plus a linker-map-based footprint report'],
    'https://github.com/Vanderhell/axiom-one'),
  primitive('graygyre','GrayGyre',
    'Adjacent logical indices can cluster in the same page, bank or logical cell even when a small deterministic spread would improve placement.',
    'An allocation-free, table-free C primitive maps indices with a self-inverse Gray-code shear, spreading local neighbours across configured logical cells while retaining an exact inverse through the same mapping call.',
    ['Gray code','data placement','branchless','table-free'],
    ['Spread deterministic record placement across logical pages or banks','Place DMA descriptors or burst-interleaved data without lookup tables','Map an index repeatedly in a hot loop after one configuration step','Permute an array in place without a visited bitmap'],
    ['Not encryption, cryptography, hashing, wear levelling, error correction or a full-cycle scheduler','The domain size must be a power of two','The mapping contains fixed points; it is a placement permutation, not a traversal order'],
    '#include "graygyre.h"\n\ngraygyre_config cfg;\ngraygyre_config_init(&cfg, 256u, 4u);\nuint32_t physical = graygyre_map_config(logical, &cfg);\nuint32_t original = graygyre_map_config(physical, &cfg);\n/* original == logical: the transform is self-inverse. */',
    'Logical index → Gray-code shear → logical cell + local offset → physical index',
    ['Configured mapping is branchless, integer-only and has no hidden state','ESP32-S3 hardware measurements and a tested configured-map size are documented separately from optimisation-profile caveats','Cortex-M0+/M4/M33 and RV32I/RV32IM are documented as compile/static-validated targets'],
    'https://github.com/Vanderhell/GrayGyre'),
  primitive('skipspace','SkipSpace',
    'Large constrained search spaces are often implicit: materialising the tree or retaining every explored prefix exceeds embedded memory budgets.',
    'A heap-free traversal primitive represents each prefix with compact sufficient state, counts valid continuations using bounded saturating arithmetic, and lets the caller visit or skip an entire subtree without materialising the search tree.',
    ['implicit search','subtree skipping','heap-free','saturating count'],
    ['Traverse a modeled constrained space with fixed caller-owned workspace','Count a subtree before deciding whether to visit or skip it','Keep navigation state compact when equivalent prefixes have equivalent futures','Use sparse skip checks in a large deterministic exploration'],
    ['It is not a general solver, AI framework, vector database or universal search engine','The modeled transition table must preserve future-relevant behaviour in its sufficient state','count/can_skip cost substantially more than push/pop; V1 does not put rank/unrank on the hot path'],
    '#include "skipspace.h"\n\n/* Configure the modeled transition table and caller-owned workspace. */\n/* push() updates sufficient state; count()/can_skip() decide a subtree. */\n/* No search tree is allocated or materialised. */',
    'Prefix → sufficient state → bounded subtree count → visit or skip subtree',
    ['The portable C core has no Arduino or ESP-IDF dependency and no dynamic allocation','V1 defines navigation, bounded/saturating count, can_skip and workspace sizing, with depth bounded at 1000','An ESP32-S3 uint32_t, 31-state, K=32 profile is documented with approximately 227,834 visited nodes/s using sparse skip checks'],
    'https://github.com/Vanderhell/skipspace')
];
Object.assign(unavailable,{problem:'Trainable text compression benefits from frequency-aware coding rather than a fixed generic codec.',solution:'Pure C99, MIT trainable frequency-optimized text codec with v2 and matrix-based v3 formats, including HIER4/HIER8 nested matrices.',status:'v0.4.3',version:'v0.4.3',lastVerified:VERIFIED,license:'MIT',language:'C99',platform:'Portable C99; external, embedded and amortized deployment objectives',tags:['text codec','trainable','matrix v3'],use:['Train from representative text','Use v2 or matrix-based v3 streams','Choose a documented deployment objective'],limits:['Compression trade-offs depend on the selected corpus and objective','Benchmark interpretation requires the documented corpus and configuration'],code:'#include "loxc.h"\n/* Train or load a documented model, then encode/decode via the public API. */',flow:'Training corpus → codec model → encode/decode API → v2 or v3 stream',evidence:['README documents trainer, CLI, simple API, examples, tests, benchmarks and technical documentation','v3 documents HIER4/HIER8 nested matrices and diagonal cells that save one coordinate value'],repo:'https://github.com/Vanderhell/loxc'});
Object.assign(projects.find(p=>p.slug==='microcrypt'),{status:'v3.0.1',version:'v3.0.1',solution:'C99 cryptographic primitives: SHA-256, HMAC-SHA256, AES-128, AES-128-CBC and AES-128-GCM with AEAD, AAD and secure-clearing helpers.',tags:['crypto primitives','AEAD'],use:['Hash a firmware buffer','Compute and verify HMAC-SHA256','Use AES-128-GCM through its documented AEAD interface'],limits:['No audit, proof, FIPS or side-channel-resistance claim','Table-based AES is unsuitable against observable cache/timing/power attackers','Follow documented nonce and key requirements'],evidence:['Repository documents tests, verification information and the v3.0.1 API surface']});
for(const p of [...projects,toolkit,pro,unavailable]){if(p.version==='Development')p.version=null;p.version??=(p.status.match(/v\d+(?:\.\d+)+/)||[null])[0];p.tags=[...new Set(p.tags||[])];delete p.lastVerified;}
// A micro* repository belongs in the Micro Toolkit even when its original
// source record used the catch-all project group.
for(const p of [...projects,toolkit])if(/^micro/i.test(p.slug))p.group='Micro-toolkit';
unavailable.lastVerified=VERIFIED;
projects.find(p=>p.slug==='microcrypt').lastVerified=VERIFIED;
// License audit rule: an explicit repository LICENSE is primary evidence.
// GitHub's SPDX detector is only supplemental metadata (LOX Dust: MIT LICENSE).
Object.assign(projects.find(p=>p.slug==='loxdust'),{license:'MIT'});
Object.assign(projects.find(p=>p.slug==='loxdb'),{
  status:'v1.5.3',version:'v1.5.3',
  solution:'Predictable-memory C99 database with key-value, time-series and small relational engines, optional WAL recovery, and direct installation from PlatformIO or the Arduino Library Manager.',
  channels:['PlatformIO Registry','Arduino Library Manager'],
  use:['Install it from the PlatformIO Registry','Find and install loxdb in the Arduino Library Manager','Store configuration or binary state by key','Keep typed telemetry streams with retention policies','Use small indexed fixed-schema tables','Recover a storage-backed database after an interrupted write'],
  evidence:['The public repository publishes PlatformIO library.json and Arduino library.properties manifests','595 microtest cases across 61 C test files plus one C++ wrapper test are documented by the current repository','Evidence matrix separates source-visible, host-tested and hardware claims','ESP32-S3 published measurements use an in-RAM flash-like backend, not physical NOR or brownout testing']
});
projects.find(p=>p.slug==='loxdb').lastVerified='2026-08-17';
Object.assign(projects.find(p=>p.slug==='ironfamily-fileengine'),{repo:'https://github.com/Vanderhell/IronFamily.FileEngine'});
const status=p=>{const s=p.status.toLowerCase();return s.includes('commercial')?'Commercial':s.includes('experiment')?'Experimental':s.includes('verification')||s.includes('repair')?'Verification':/not declared release-ready|unreleased|pre-1\.0/.test(s)?'Development':s.includes('release')||/^v\d/.test(s)?'Stable':'Development'};
const head=(title,description,url,p='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="google-site-verification" content="ZcLes6Gcp4HDDqHMF7uUlssy00WjDbP_rXlndEgeJZw"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://vanderhell.github.io/${url}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="https://vanderhell.github.io/${url}"><meta property="og:image" content="https://vanderhell.github.io/lox-logo.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${p}favicon.svg"><link rel="stylesheet" href="${p}assets/site.css"><script defer src="${p}analytics-config.js"></script><script defer src="${p}assets/analytics.js"></script><script defer src="${p}assets/site.js"></script></head>`;
const nav=(p='',current='')=>`<a class="skip" href="#main">Skip to content</a><header class="site-header"><nav class="nav wrap" aria-label="Main navigation"><a class="brand" href="${p}index.html"><span class="site-title">Vanderhell <strong>Development</strong><small>C · C++ · C# · Embedded Systems</small></span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="nav-links">Menu</button><div class="nav-links" id="nav-links"><a href="${p}index.html" ${current==='home'?'aria-current="page"':''}>Home</a><a href="${p}lox-family.html">LOX Family</a><a href="${p}micro-toolkit.html">Micro Toolkit</a><a href="${p}axiom-one.html">Axiom One</a><a href="${p}beyond-lox.html">Beyond LOX</a><a href="${p}about.html">About</a><a href="https://github.com/Vanderhell">GitHub</a></div></nav></header>`;
const footer=p=>`<footer class="site-footer"><div class="wrap footer-row"><span>© 2026 Vanderhell</span><a href="mailto:Vanderhell@gmail.com">Vanderhell@gmail.com</a></div></footer>`;
const card=(p,prefix='')=>{prefix=typeof prefix==='string'?prefix:'';const meta=[status(p),p.version,p.language,p.license].filter(Boolean).map(esc).join(' · ');return `<article class="portfolio-card" data-project-card data-group="${esc(p.group)}"><h3>${esc(p.name)}</h3><p>${esc(p.solution)}</p><small>${meta}</small><a href="${prefix}projects/${p.slug}.html">Open project →</a></article>`};
const flow=p=>`<div class="flow">${p.flow.split('→').map((x,i)=>`<span><b>${i+1}</b>${esc(x.trim())}</span>`).join('<i>→</i>')}</div>`;
const detail=p=>{const scenarios=new Set(['loxdb','loxbudget','microsh','loxboot','iotspool','panicdump']);const hasScenario=scenarios.has(p.slug);return `${head(`${p.name} — Vanderhell portfolio`,`${p.name}: ${p.problem}` ,`projects/${p.slug}.html`,'../')}<body data-project="${p.slug}">${nav('../')}<main id="main"><header class="hero product-hero"><div class="wrap"><div class="kicker">${esc(p.group)}</div><h1>${esc(p.name)}</h1><p class="slogan">${esc(p.problem)}</p><p>${esc(p.solution)}</p><div class="badges"><span class="badge status-${status(p).toLowerCase()}">${status(p)}</span><span class="badge">${esc(p.version)}</span><span class="badge">${esc(p.license)}</span><span class="badge">${esc(p.language)}</span></div><div class="actions"><a class="button primary" href="${p.repo}">GitHub</a><a class="button secondary" href="#quick-start">Quick Start</a></div><dl class="meta"><div><dt>Last verified</dt><dd>${p.lastVerified}</dd></div><div><dt>Platform scope</dt><dd>${esc(p.platform)}</dd></div></dl></div></header><section class="section"><div class="wrap content-grid"><article class="content"><h2>What it solves</h2><p>${esc(p.problem)}</p><h2>How it works</h2>${flow(p)}<h2>Use it when</h2><div class="use-grid">${p.use.map(x=>`<div class="panel">${esc(x)}</div>`).join('')}</div><h2 id="quick-start">Quick Start</h2><div class="code-wrap"><pre><code>${esc(p.code)}</code></pre></div>${hasScenario?`<h2>Real scenarios</h2><div class="scenario-stack">${p.use.slice(0,3).map((x,i)=>`<section class="scenario"><span class="scenario-no">0${i+1}</span><h3>${esc(x)}</h3><p>${esc(p.solution)}</p></section>`).join('')}</div>`:''}<h2>Engineering evidence</h2><ul>${p.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Known limits</h2><ul>${p.limits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><aside class="side panel"><strong>Project data</strong><a href="${p.repo}">Repository ↗</a><p><small>Verified ${p.lastVerified}</small></p></aside></div></section></main>${footer('../')}</body></html>`};
const groups=[['LOX Family',projects.filter(p=>p.group==='LOX')],['Micro Toolkit',projects.filter(p=>p.group==='Micro-toolkit')],['Axiom One primitives',primitives],['Beyond LOX',projects.filter(p=>p.group==='Beyond LOX')]];
const family=(name,list,file)=>`${head(`${name} — Vanderhell Development`,`${name} projects.`,file)}<body>${nav('')}<main id="main"><header class="hero compact-hero"><div class="wrap"><div class="kicker">Project family</div><h1>${name}</h1></div></header><section class="section"><div class="wrap"><div class="portfolio-cards">${list.map(p=>card(p)).join('')}</div></div></section></main>${footer('')}</body></html>`;
const axiomFamily=`${head('Axiom One primitives — Vanderhell Development','Deterministic, allocation-free C primitives for bounded embedded problems.','axiom-one.html')}<body>${nav('')}<main id="main"><header class="hero compact-hero"><div class="wrap"><div class="kicker">Primitive family</div><h1>Axiom One primitives</h1><p>Three independent building blocks for bounded embedded work: a broad deterministic module library, table-free data placement, and heap-free traversal of implicit constrained spaces.</p></div></header><section class="section"><div class="wrap content-narrow"><h2>Small primitives, explicit boundaries</h2><p>This family is intentionally not a framework. Each component solves one narrow problem with deterministic behaviour, caller-owned state and no hidden allocation. They can stand alone in firmware where memory, timing and integration boundaries matter.</p><div class="portfolio-cards">${primitives.map(p=>card(p)).join('')}</div><h2>How the pieces differ</h2><div class="use-grid"><div class="panel"><strong>Axiom One</strong><br>22 general-purpose C99 primitives for scheduling, signal conditioning, protocol state and fixed-capacity containers.</div><div class="panel"><strong>GrayGyre</strong><br>A self-inverse Gray-code placement transform that spreads neighbouring indices across logical cells.</div><div class="panel"><strong>SkipSpace</strong><br>A sufficient-state traversal core that counts and skips subtrees without constructing the search tree.</div></div></div></section></main>${footer('')}</body></html>`;
const selected=['loxdb','loxc','loxboot','microcrypt','panicdump','iotspool'].map(s=>s==='loxc'?unavailable:projects.find(p=>p.slug===s));
const home=`${head('Vanderhell Development — systems and embedded software','Native systems and embedded software: storage, recovery, diagnostics and communication.','index.html')}<body>${nav('','home')}<main id="main"><header class="hero portfolio-hero"><div class="wrap"><div class="kicker">Independent systems software development</div><h1>Vanderhell Development</h1><p class="lede">Small native components and systems for constrained environments: storage, recovery, diagnostics, communication and deterministic control.</p><div class="actions"><a class="button primary" href="#selected">Selected projects</a><a class="button secondary" href="https://github.com/Vanderhell">GitHub</a></div></div></header><section class="section"><div class="wrap"><h2>What I build</h2><div class="areas"><article class="area"><h3>Persistent systems</h3><p>Databases, logs, configuration and power-loss recovery.</p></article><article class="area"><h3>Diagnostics & recovery</h3><p>Crash evidence, watchdogs, boot recovery and alarms.</p></article><article class="area"><h3>Communication</h3><p>LAN, mesh, queues and constrained protocols.</p></article><article class="area"><h3>Low-level building blocks</h3><p>Deterministic C components with explicit ownership and limits.</p></article></div></div></section><section class="section selected" id="selected"><div class="wrap"><h2>Selected projects</h2><div class="portfolio-cards">${selected.map(p=>card(p)).join('')}</div></div></section><section class="section family-section"><div class="wrap"><h2>Project families</h2><div class="families"><a href="lox-family.html"><h3>LOX Family</h3><p>Persistent state, recovery and diagnostics.</p></a><a href="micro-toolkit.html"><h3>Micro Toolkit</h3><p>Small independent components.</p></a><a href="axiom-one.html"><h3>Axiom One primitives</h3><p>Focused deterministic primitives for embedded constraints.</p></a><a href="beyond-lox.html"><h3>Beyond LOX</h3><p>Specialised systems work.</p></a></div><p><a href="all-projects.html">Find a project by engineering problem →</a></p></div></section></main>${footer('')}</body></html>`;
const all=[...projects,...primitives,toolkit,pro,unavailable];
const catalog=`${head('All Projects — Vanderhell Development','Complete project catalogue.','all-projects.html')}<body>${nav('')}<main id="main"><header class="hero compact-hero"><div class="wrap"><h1>All projects</h1><p>Storage, recovery, diagnostics, connectivity and focused C components.</p></div></header><section class="section"><div class="wrap"><label class="search-label">Search projects <input id="project-search" type="search"></label><div class="portfolio-cards catalog-cards">${all.map(card).join('')}</div><p class="empty" hidden>No matching project.</p></div></section></main>${footer('')}</body></html>`;
const about=`${head('About Vanderhell Development','Independent systems and embedded software development.','about.html')}<body>${nav('','about')}<main id="main"><header class="hero compact-hero"><div class="wrap"><h1>Systems software, with boundaries made explicit.</h1><p>Independent developer focused on C/C++, embedded systems and relevant C#/.NET tooling.</p></div></header><section class="section"><div class="wrap content-narrow"><h2>Engineering focus</h2><p>Architecture, implementation, tests, documentation and release engineering for storage, persistence, diagnostics, communication, deterministic behaviour and constrained systems.</p><h2>Representative work</h2><div class="portfolio-cards">${selected.slice(0,4).map(card).join('')}</div></div></section></main>${footer('')}</body></html>`;
const enhanceHome=text=>text
  .replace('<div class="kicker">Independent systems software development</div>','<div class="kicker" data-typewriter>Independent systems software development</div>')
  .replace('<h1>Vanderhell Development</h1>','<h1>Embedded systems that recover, explain and endure.</h1>')
  .replace('<h3>LOX Family</h3><p>Persistent state, recovery and diagnostics.</p>','<h3>LOX — Liquid Oxygen</h3><p>Liquid Oxygen for Embedded Systems: focused storage, recovery, control and diagnostic components.</p>')
  .replace('<p class="lede">Small native components and systems for constrained environments: storage, recovery, diagnostics, communication and deterministic control.</p>','<div class="hero-focus" data-hero-focus><p class="lede">Small native components and systems for constrained environments.</p><div class="focus-options" aria-label="Explore engineering focus"><button type="button" data-focus="storage" aria-pressed="true">Storage</button><button type="button" data-focus="recovery" aria-pressed="false">Recovery</button><button type="button" data-focus="diagnostics" aria-pressed="false">Diagnostics</button><button type="button" data-focus="communication" aria-pressed="false">Communication</button><button type="button" data-focus="control" aria-pressed="false">Deterministic control</button></div><p class="focus-output" aria-live="polite">Predictable persistence for configuration, telemetry and small structured data.</p></div>')
  .replace('<h2>Project families</h2><div class="families">',`<h2>Project families</h2><p class="family-intro">Four clear paths through the portfolio: product systems, micro libraries, deterministic primitives and specialised independent work.</p><div class="family-stats" aria-label="Project family totals"><span><b data-count="${groups[0][1].length}">0</b> LOX projects</span><span><b data-count="${groups[1][1].length}">0</b> micro libraries</span><span><b data-count="${groups[2][1].length}">0</b> primitives</span><span><b data-count="${groups[3][1].length}">0</b> additional projects</span></div><div class="families">`)
  .replace('<div class="actions"><a class="button primary" href="#selected">Selected projects</a><a class="button secondary" href="https://github.com/Vanderhell">GitHub</a></div>','<div class="actions hero-actions"><a class="button primary" href="#selected">Selected projects</a><a class="button secondary" href="all-projects.html">Find by engineering problem &rarr;</a><a class="button secondary" href="https://github.com/Vanderhell">GitHub</a></div>');
const enhanceLoxdb=text=>text.replace('<div class="badges">','<div class="install-channels" aria-label="Available package managers"><strong>Install from</strong><span>PlatformIO Registry</span><span>Arduino Library Manager</span><small>Search for <b>loxdb</b> in either library manager.</small></div><div class="badges">');
const enhanceLoxFamily=text=>text
  .replaceAll('LOX Family projects.','Liquid Oxygen for Embedded Systems: focused storage, recovery, control and diagnostic projects.')
  .replace('<h1>LOX Family</h1>','<h1>LOX — Liquid Oxygen for Embedded Systems</h1><p class="lox-manifesto">Small, explicit components that give constrained firmware room to recover, explain decisions and keep moving.</p><button class="rocket-launch" type="button" data-rocket-launch aria-label="Launch the LOX rocket"><span>Launch the LOX mission</span><svg viewBox="0 0 160 80" aria-hidden="true"><path class="rocket-route" d="M12 65C52 62 67 42 90 30s38-13 58-22"/><g class="rocket"><path d="M0-9C13-9 22-4 29 0 22 4 13 9 0 9L-7 0z"/><path d="M5-9l-6-8h10l8 9M5 9l-6 8h10l8-9"/><circle cx="12" cy="0" r="4"/></g><g class="rocket-flame"><path d="M-8 0l-11-6 4 6-4 6z"/></g></svg></button>');
const write=(file,text)=>fs.writeFileSync(path.join(ROOT,file),text.replaceAll('>LOX Family</a>','>LOX / Liquid Oxygen</a>').replaceAll('<div class="kicker">LOX</div>','<div class="kicker">LOX · Liquid Oxygen for Embedded Systems</div>').replaceAll('Beyond LOX','Additional projects').replaceAll('undefined','Not audited against current README/docs'));
write('index.html',enhanceHome(home));write('lox-family.html',enhanceLoxFamily(family('LOX Family',groups[0][1],'lox-family.html')));write('micro-toolkit.html',family('Micro Toolkit',groups[1][1],'micro-toolkit.html'));write('axiom-one.html',axiomFamily);write('beyond-lox.html',family('Beyond LOX',groups[3][1],'beyond-lox.html'));write('all-projects.html',catalog);write('about.html',about);
for(const p of all)write(`projects/${p.slug}.html`,p.slug==='loxdb'?enhanceLoxdb(detail(p)):detail(p));
const urls=['','lox-family.html','micro-toolkit.html','axiom-one.html','beyond-lox.html','all-projects.html','about.html',...all.map(p=>`projects/${p.slug}.html`)];write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>https://vanderhell.github.io/${u}</loc></url>`).join('')}</urlset>`);write('robots.txt','User-agent: *\nAllow: /\nSitemap: https://vanderhell.github.io/sitemap.xml\n');
